name: tsdm_client
description: 天使动漫论坛第三方跨平台客户端
repository: https://github.com/realth000/tsdm_client
homepage: https://github.com/realth000/tsdm_client
issue_tracker: https://github.com/realth000/tsdm_client/issues
publish_to: "none"

version: 1.0.0+35

environment:
  flutter: ">=3.27.0 <4.0.0"
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  # Workaround for dart_mappable build issue
  ansicolor: any
  args: ^2.6.0
  bbob_dart: ^0.2.1
  bloc: ^8.1.4
  chat_bottom_container: ^0.3.0
  # Blocked by flutter
  collection: any
  cookie_jar: ^4.0.8
  dart_mappable: ^4.3.0
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  dio_brotli_transformer: ^2.0.0
  dio_cookie_manager: ^3.1.1
  drift: ^2.22.1
  # For drift
  drift_dev: ^2.22.1
  drift_flutter: ^0.2.3
  easy_refresh: ^3.4.0
  equatable: ^2.0.7
  extended_nested_scroll_view: ^6.2.1
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_avif:
    path: ./packages/flutter_avif/flutter_avif
  flutter_bbcode_editor:
    path: ./packages/flutter_bbcode_editor
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+3
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  gitsumu: ^0.5.3
  go_router: ^14.6.2
  html: ^0.15.5
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  material_design_icons_flutter: ^7.0.7296
  path: any
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  responsive_framework: ^1.5.1
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  slang: ^4.4.0
  slang_flutter: ^4.4.0
  # For drift
  sqlite3: ^2.5.0
  # For drift
  sqlite3_flutter_libs: ^0.5.27
  stream_transform: ^2.1.1
  super_sliver_list: ^0.4.1
  surf_lint_rules: ^3.1.0
  system_theme: ^3.1.2
  talker: ^4.5.2
  talker_flutter: ^4.5.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web: ^1.1.0
  widget_zoom: ^0.0.4
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.14
  # Blocked by flutter_l18n, analyzer and collection
  custom_lint: ^0.6.8
  dart_mappable_builder: ^4.3.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  # Blocked by dart_mappable_builder
  json_serializable: ^6.9.0
  pyramid_lint: ^2.0.1
  slang_build_runner: ^4.4.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/emoji/
    - assets/text/

# To generate png from svg, run:
# rsvg-convert -w 200 -h 300 tsdm_client.svg -o tsdm_client-large-200x300.png
flutter_launcher_icons:
  image_path: "assets/images/tsdm_client-large-300x300.png"
  ios: true
  macos:
    generate: true
    image_path: "assets/images/tsdm_client-large-300x300.png"
  windows:
    generate: true
    image_path: "assets/images/tsdm_client-large-300x300.png"
  web:
    generate: true
    image_path: "assets/images/tsdm_client-large-300x300.png"
  android: true
