name: tsdm_client
description: 天使动漫论坛官方跨平台客户端
repository: https://github.com/realth000/tsdm_client
homepage: https://github.com/realth000/tsdm_client
issue_tracker: https://github.com/realth000/tsdm_client/issues
publish_to: "none"

version: 1.6.0+45

environment:
  flutter: ">=3.29.0 <4.0.0"
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  args: ^2.6.0
  bbob_dart: ^0.2.1
  bloc: ^9.0.0
  chat_bottom_container: ^0.3.1
  # Blocked by flutter
  collection: any
  cookie_jar: ^4.0.8
  dart_bbcode_parser:
    path: ./packages/dart_bbcode_parser
  dart_bbcode_web_colors:
    path: ./packages/dart_bbcode_web_colors
  dart_mappable: ^4.5.0
  dart_quill_delta: ^10.8.3
  dio: ^5.8.0+1
  dio_brotli_transformer: ^2.0.0
  dio_cookie_manager: ^3.2.0
  drift: ^2.26.0
  # For drift
  drift_dev: ^2.26.0
  drift_flutter: ^0.2.4
  easy_refresh: ^3.4.0
  equatable: ^2.0.7
  extended_nested_scroll_view: ^6.2.1
  file_picker: ^10.1.2
  flex_color_picker: ^3.7.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_avif:
    path: ./packages/flutter_avif/flutter_avif
  flutter_bbcode_editor:
    path: ./packages/flutter_bbcode_editor
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  gitsumu: ^0.7.0
  go_router: ^15.0.0
  html: ^0.15.5+1
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2811.0
  path: any
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  photo_view: ^0.15.0
  responsive_framework: ^1.5.1
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  # For drift
  smooth_sheets: ^0.11.4
  sqlite3: ^2.7.5
  # For drift
  sqlite3_flutter_libs: ^0.5.32
  stream_transform: ^2.1.1
  super_sliver_list: ^0.4.1
  system_theme: ^3.1.2
  talker: ^4.7.2
  talker_flutter: ^4.7.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web: ^1.1.1
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  dart_mappable_builder: ^4.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  pyramid_lint: ^2.0.3
  slang_build_runner: ^4.7.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/emoji/
    - assets/text/

# To generate png from svg, run:
# rsvg-convert -w 200 -h 300 tsdm_client.svg -o tsdm_client-large-200x300.png
flutter_launcher_icons:
  image_path: "assets/images/tsdm_client-large-300x300.png"
  ios: true
  macos:
    generate: true
    image_path: "assets/images/tsdm_client-large-300x300.png"
  windows:
    generate: true
    image_path: "assets/images/tsdm_client-large-300x300.png"
  web:
    generate: true
    image_path: "assets/images/tsdm_client-large-300x300.png"
  android: true
