name: tsdm_client
description: 天使动漫论坛官方跨平台客户端
repository: https://github.com/realth000/tsdm_client
homepage: https://github.com/realth000/tsdm_client
issue_tracker: https://github.com/realth000/tsdm_client/issues
publish_to: "none"

version: 1.14.0+54

environment:
  flutter: ">=3.41.0 <4.0.0"
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  args: ^2.6.0
  bloc: ^9.2.0
  chat_bottom_container: ^0.4.0
  # Blocked by flutter
  collection: any
  cookie_jar: ^4.0.8
  dart_bbcode_parser:
    path: ./packages/dart_bbcode_parser
  dart_bbcode_web_colors:
    path: ./packages/dart_bbcode_web_colors
  dart_mappable: ^4.6.1
  dart_quill_delta: ^10.8.3
  dio: ^5.9.1
  dio_brotli_transformer: ^2.0.0
  dio_cookie_manager: ^3.3.0
  drift: ^2.31.0
  # For drift
  drift_dev: ^2.31.0
  drift_flutter: ^0.2.8
  easy_refresh: ^3.4.0
  equatable: ^2.0.8
  file_picker: ^10.3.7
  flex_color_picker: ^3.8.0
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_avif:
    path: ./packages/flutter_avif/flutter_avif
  flutter_bbcode_editor:
    path: ./packages/flutter_bbcode_editor
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_styled_toast: ^2.3.0
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  fpdart: ^1.2.0
  get_it: ^9.2.0
  gitsumu: ^0.7.2
  go_router: ^17.1.0
  html: ^0.15.5+1
  http: ^1.6.0
  image_picker: ^1.2.1
  json_annotation: ^4.9.0
  loading_indicator_m3e: ^0.1.1
  m3e_design: ^0.2.1
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2892.0
  native_flutter_proxy: ^0.2.3
  path: any
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  responsive_framework: ^1.5.1
  rxdart: ^0.28.0
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  slang: ^4.12.1
  slang_flutter: ^4.12.1
  smooth_sheets: ^0.15.0
  # For drift
  sqlite3: ^2.9.4
  # For drift
  sqlite3_flutter_libs: ^0.5.41
  stream_transform: ^2.1.1
  super_sliver_list: ^0.4.1
  system_network_proxy:
    path: ./packages/flutter_system_network_proxy/system_network_proxy
  system_theme:
    git:
      url: https://github.com/realth000/system_theme
      path: system_theme
      ref: 0e66e563ccf48735066a81b7eb55811b3af3c0d7
  talker: ^5.1.13
  talker_flutter: ^5.1.13
  universal_html: ^2.3.0
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  web: ^1.1.1
  wheel_choice: ^1.2.0
  window_manager: ^0.5.1

dev_dependencies:
  build_runner: ^2.11.1
  custom_lint: ^0.8.0
  dart_mappable_builder: ^4.6.4
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.2
  pyramid_lint: ^2.4.0
  slang_build_runner: ^4.12.1
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/emoji/
    - assets/text/

flutter_launcher_icons:
  image_path: "assets/images/tsdm_client.png"
  ios: true
  macos:
    generate: true
    image_path: "assets/images/tsdm_client.png"
  windows:
    generate: true
    image_path: "assets/images/tsdm_client.png"
  web:
    generate: true
    image_path: "assets/images/tsdm_client.png"
  android: true
